name: bandgaps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - pydantic=1.9.1
  - protobuf=3.19.1
  - jupyter=1.0.0
  - ipytest=0.12.0
  - rich=13.3.3
  - ngspice=38
  # Dev
  - pytest
  - coverage
  - pytest-cov
  - pre-commit
  - black
  - pip
  - pip:
    - spyci==1.0.2
    - hdl21==4.0.0
    - hdl21schematicimporter==1.0.dev0
